---
- name: manage web server
  hosts: all
  become: yes
  tasks:

    #с чем мы работаем прямо сейчас
    - include: playbooks/get_family.yaml

    - include: playbooks/yum_playbook.yaml
      when: rpm_like
    
    - include: playbooks/apt_playbook.yaml
      when: debian_like
    
    - include: playbooks/static_ip_on_deb
      when: debian_like

