---
- name: manage web server
  hosts: all
  become: yes
  tasks:

    #с чем мы работаем прямо сейчас
    - include: playbooks/get_family.yaml

    #заходим и узнаем кто мы
    # - name: register yum
    #   stat:
    #     path: /bin/yum
    #   register: yum_stat

    # - name: register apt
    #   stat: 
    #     path: /bin/apt
    #   register: apt_stat

    - include: playbooks/yum_playbook.yaml
      when: rpm_like
    
    - include: playbooks/apt_playbook.yaml
      when: debian_like

