---

# - name: get name of netplan config file
#   shell: ls -1 /etc/netplan/
#   register: netplan_filename

# - name: find and replace
#   set_fact:
#     full_netplan_path: "{{ '/etc/netplan/' + netplan_filename.stdout }}"

- name: replace in netplan config
  replace:
    path: /tmp/kal.txt
    regexp: ^([01]?\d\d?|2[0-4]\d|25[0-5])(?:\.(?:[01]?\d\d?|2[0-4]\d|25[0-5])){3}(?:/[0-2]\d|/3[0-2])?$
    replace: '[10.0.10.1/16]'

