---

- name: get name of netplan config file
  shell: ls -1 /etc/netplan/
  register: netplan_filename

- name: find and replace
  set_fact:
    full_netplan_path: "{{ '/etc/netplan/' + netplan_filename.stdout }}"

- name: replace in netplan config
  replace:
    path: 'full_netplan_path'
    regexp: 'x.x.x.x/x'
    replace: '10.0.10.1/16'

