---

# - name: get name of netplan config file
#   shell: ls -1 /etc/netplan/
#   register: netplan_filename

# - name: find and replace
#   set_fact:
#     full_netplan_path: "{{ '/etc/netplan/' + netplan_filename.stdout }}"

- name: replace in netplan config
  replace:
    path: /tmp/kal.txt
    regexp: ([0-9]{1,3}[\.]){3}[0-9]{1,3}
    replace: '[10.0.10.1/16]'

