---

- name: update cache
  yum:
    update_cache: yes

- name: download some packeges
  yum:
    name:
      - httpd
      - mariadb-server

- name: cpoy html page
  copy: 
    src: ~/my_awesome_ansible/files/start_page_centos.html
    dest: /var/www/html/index.html
    owner: root
    mode: 0644

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: true

- name: restart mariadb
  service: 
    name: mariadb
    state: restarted
    enabled: yes

- name: enable connection to httpd
  firewalld: 
    service: http
    permanent: true
    state: enabled

- name: restart firewall
  service:
    name: firewalld
    state: restarted
   
